### ISSUE TITLE
yarn dev时出现问题

### ISSUE THREAD

**Issue by liuerhang** [OrcaXS/mangaEditor#1]
error: Expected indentation of 4 spaces but found 6 (indent) at src/views/Editor.vue:171:1:
  169 |     this.getFile({ id });
  170 |     // if (typeof this.$store.state.canvas.file[id] === 'object') {
> 171 |       // this.isStorageReady = true;
      | ^
  172 |       // window.location.reload(true);
  173 |     // } else {
  174 |       // eslint-disable-next-line no-underscore-dangle

error: Expected indentation of 4 spaces but found 6 (indent) at src/views/Editor.vue:172:1:
  170 |     // if (typeof this.$store.state.canvas.file[id] === 'object') {
  171 |       // this.isStorageReady = true;
> 172 |       // window.location.reload(true);
      | ^
  173 |     // } else {
  174 |       // eslint-disable-next-line no-underscore-dangle
  175 |       // this.$eventHub.$on('storageReady', () => {

error: Expected indentation of 4 spaces but found 6 (indent) at src/views/Editor.vue:174:1:
  172 |       // window.location.reload(true);
  173 |     // } else {
> 174 |       // eslint-disable-next-line no-underscore-dangle
      | ^
  175 |       // this.$eventHub.$on('storageReady', () => {
  176 |       //   this.isStorageReady = true;
  177 |       // });

error: Expected indentation of 4 spaces but found 6 (indent) at src/views/Editor.vue:175:1:
  173 |     // } else {
  174 |       // eslint-disable-next-line no-underscore-dangle
> 175 |       // this.$eventHub.$on('storageReady', () => {
      | ^
  176 |       //   this.isStorageReady = true;
  177 |       // });
  178 |     // }

error: Expected indentation of 4 spaces but found 6 (indent) at src/views/Editor.vue:176:1:
  174 |       // eslint-disable-next-line no-underscore-dangle
  175 |       // this.$eventHub.$on('storageReady', () => {
> 176 |       //   this.isStorageReady = true;
      | ^
  177 |       // });
  178 |     // }
  179 |   },

error: Expected indentation of 4 spaces but found 6 (indent) at src/views/Editor.vue:177:1:
  175 |       // this.$eventHub.$on('storageReady', () => {
  176 |       //   this.isStorageReady = true;
> 177 |       // });
      | ^
  178 |     // }
  179 |   },
  180 | 

6 errors found.
6 errors potentially fixable with the `--fix` option.

没学过vue，还抱了一堆warning，问下问题在哪里

**Comment by OrcaXS** [comment]
https://github.com/OrcaXS/mangaEditor/commit/16b2868c8d4e1b9a846d6d4427bf6a78740e3d16
Fixed.
